spring.application.name=api
server.port=8082

spring.data.mongodb.uri=mongodb+srv://admin23:admin123@cluster0.noan6i7.mongodb.net/smartcampus?authSource=admin

jwt.secret=94a08da1fecb6e4b23d9bba4c4e0b57e7939b4b92b6a7a5e4d29188e6a1c51d6
jwt.expiration=86400000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=17010759492-qopksamatk088dmc4clpeaui0l8h7fp0.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
# Gemini AI
gemini.api.key=AIzaSyDUW2N9kGH_YUaouDO4kej9yvb0R3yG_fs
